name = "blog-a-cifra"
compatibility_date = "2024-10-20"

[build]
command = "npm ci && npm run build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"
NPM_FLAGS = "--production=false"

pages_build_output_dir = "out"